### ISSUE TITLE
Cannot use library , bricks arduino nano 33 iot

### ISSUE THREAD

**Issue by TalSomech** [khoih-prog/SAMD_TimerInterrupt#28]
Arduino IDE version: 2.0.3
Arduino SAMD Core Version 1.8.13
OS: Windows 10
board: Arduino nano 33 IOT
Context:
I encountered a problem while using this library by the following code

```cpp
    if (ITimer.attachInterruptInterval(HW_TIMER_INTERVAL_MS * 50, TimerHandler)) {
        Serial.print(F("Starting ITimer OK, millis() = "));
        Serial.println(millis());
    } else
        Serial.println(F("Can't set ITimer. Select another freq. or timer"));
```

on my arduino, but while uploading the sketch i encountered a problem which the computer wont recognize the arduino 
and cant upload anymore unless i press twice on the reset button

**Comment by khoih-prog** [comment]
Hi @TalSomech 

It normally requires certain level of knowledge and skills to use any interrupt.

Try first to use a simple example to be **familiarized** yourself before moving forward.

The **ISR** (Interrupt Service Routine), which you didn't show, is extremely crucial and just a wrong line can brick any board.

I'm sure this this not an issue of the library, and suggest you get help from Arduino Forum, just remember to post the whole [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) so that anyone can duplicate and help you fix the programming problem.

Good Luck,
