### ISSUE TITLE
The src_cpp->src/src_h->src hack from the README will not avoid multiple definitions when SAMD_TimerInterrupt.h is included in multiple project files.

### ISSUE THREAD

**Issue by foodini** [khoih-prog/SAMD_TimerInterrupt#8]
### Describe the bug

There are a number of artifacts that are defined - as opposed to just declared - in the SAMD_TimerInterrupt.h file. As a result, if you have two compilation units that #include that file, the multiple-definition problem is unavoidable. These functions should be _declared_ in the .h, but only _defined_ in the .cpp.

### Steps to Reproduce

Create a sketch with three source files, the .ino, foo.h, and foo.cpp. If main.ino and foo (either through the .cpp or the .h) include SAMD_TimerInterrupt.h, both of the object files will have definitions of a number of things (in my case; TC3_Handler, TCC0_Handler, TCC_Callback, etc.) and will be unable to link. In C++, it's impossible to use a .h with definitions in it if its declarations are needed in multiple compilation units. Since I have more than one place that depends upon SAMD_TimerInterrupt, the definitions all have to be moved.
 
### Actual behavior

sketch\Sensor_GPS.cpp.o: In function `TC3_Handler':
...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:410: multiple definition of `TC3_Handler'
...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:410: first defined here
sketch\Sensor_GPS.cpp.o: In function `TCC0_Handler':
...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:423: multiple definition of `TCC0_Handler'
sketch\MKRZero_telemetry_1.1.ino.cpp.o:...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:423: first defined here
sketch\Sensor_GPS.cpp.o:...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:399: multiple definition of `TCC_callback'
sketch\MKRZero_telemetry_1.1.ino.cpp.o:...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:399: first defined here
sketch\Sensor_GPS.cpp.o:...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:398: multiple definition of `TC3_callback'
sketch\MKRZero_telemetry_1.1.ino.cpp.o:...\Documents\Arduino\libraries\SAMD_TimerInterrupt\src/SAMDTimerInterrupt.h:398: first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino MKRZERO.

**Comment by khoih-prog** [comment]
Hi @foodini 

Thanks for your interest in the library and the bug report.

Could you please have a look at one of many issues posted in other libraries, such as [**Multiple definition errors due to non-standard naming convention** #21](https://github.com/khoih-prog/WebSockets2_Generic/issues/21)

> Normally, you get the error because of careless inclusion of any header file in any place.

I believe you, as an experienced programmer dealing with complex projects, can select to include the `SAMD_TimerHandler.h` only when necessary, not blindly include to every `h` or `cpp` file as novice programmers do.

If necessary, you can even change the `cpp` file to `hpp` file and compile OK.

---

For example. 

`MultiDef_hpp.ino`

```
#include "foo.h"

foo myFoo;

void setup() 
{
  myFoo.init();
}

void loop() 
{
  // put your main code here, to run repeatedly:
}
```
---

`foo.h`

```
#pragma once

#include "SAMDTimerInterrupt.h"

class foo
{
  public:

  foo() {};

  void init();
};

#include "foo.hpp"
```
---

`foo.hpp` (modified from `foo.cpp`)

```
#pragma once

// Many functions as in normal cpp file
#define TIMER0_INTERVAL_MS        500   //1000

// Init SAMD timer TIMER_TC3
SAMDTimer ITimer0(TIMER_TC3);

void TimerHandler0()
{
  
}

void foo::init()
{
  // Interval in microsecs
  if (ITimer0.attachInterruptInterval(TIMER0_INTERVAL_MS * 1000, TimerHandler0))
  {
    Serial.print(F("Starting  ITimer0 OK, millis() = ")); Serial.println(millis());
  }
  else
    Serial.println(F("Can't set ITimer0. Select another freq. or timer"));
}
```

---
---

Certainly, if in the future, there are too many novice users having the same issue, I'll consider split the `h` file further to `h` and `cpp` files. So far you're just the first one.

Good Luck with your project,

**Comment by khoih-prog** [comment]
Check the new enhancement in new [**SAMD_TimerInterrupt releases v1.6.0**](https://github.com/khoih-prog/SAMD_TimerInterrupt/releases/tag/v1.6.0) and the example [**multiFileProject**](examples/multiFileProject) to demo for multiple-file project.

---

### Releases v1.6.0

1. Fix `multiple-definitions` linker error. Drop `src_cpp` and `src_h` directories
2. Add example [multiFileProject](examples/multiFileProject) to demo for multiple-file project.
3. Add support to many more boards, such as `SAMD21E1xA`, `SAMD21G1xA` and`SAMD21J1xA`
4. Optimize library code by using `reference-passing` instead of `value-passing`
5. Update all examples
6. Update `Packages_Patches`
