### ISSUE TITLE
Multiple Definition Error Not fixed by swapping src_cpp or src_h with src

### ISSUE THREAD

**Issue by will63powell** [khoih-prog/SAMD_TimerInterrupt#9]
Please see the [stack overflow question](https://stackoverflow.com/questions/70108977/multiple-defintion-error-when-using-external-library-c) I posted on this bug. I have tried switching the src_cpp and src_h but the SAMDTimerInterrupt.h files are identical on all 3! 

I have tried a forward declare and including it as a cpp file instead of a header file but no luck.

Please could you adjust the src_cpp or src_h files to prevent this linker error

P.s. apart from this, the library is amazing and I am thankful for your work :)

**Comment by khoih-prog** [comment]
Hi @will63powell 

Thanks for your interest in the library and your nice words.

Check the previous issue [**The src_cpp->src/src_h->src hack from the README will not avoid multiple definitions when SAMD_TimerInterrupt.h is included in multiple project files.** #8](https://github.com/khoih-prog/SAMD_TimerInterrupt/issues/8)

Good Luck,

**Comment by will63powell** [comment]
Thanks for the quick reply. I have split the .h file into a .cpp and .h (attached)
Can you upload this to the SAMD_TimerInterrrupt/SRC_CPP for others to use as currently there is no .cpp for SAMDTimerInterrupt
[SAMDTimerInterrupt.zip](https://github.com/khoih-prog/SAMD_TimerInterrupt/files/7603967/SAMDTimerInterrupt.zip)
?

**Comment by khoih-prog** [comment]
Hi @will63powell 

The new [**SAMD_TimerInterrupt releases v1.6.0**](https://github.com/khoih-prog/SAMD_TimerInterrupt/releases/tag/v1.6.0) has just been published thanks to your bug report.

Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/SAMD_TimerInterrupt#contributions-and-thanks).

Best Regards,

---

### Releases v1.6.0

1. Fix `multiple-definitions` linker error. Drop `src_cpp` and `src_h` directories
2. Add example [multiFileProject](examples/multiFileProject) to demo for multiple-file project.
3. Add support to many more boards, such as `SAMD21E1xA`, `SAMD21G1xA` and`SAMD21J1xA`
4. Optimize library code by using `reference-passing` instead of `value-passing`
5. Update all examples
6. Update `Packages_Patches`

**Comment by will63powell** [comment]
Greatly appreciated. This timer interrupt library plays a big part in one
of my projects.
